language: python
python:
  - 2.7

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # Install conda
  - sudo apt-get update 
  # Install miniconda
  # -----------------
  - if [[ "$TRAVIS_PYTHON_VERSION" == 2* ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-3.7.0-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-3.7.0-Linux-x86_64.sh -O miniconda.sh;
    fi
    
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
   
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

  
install: 


  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment

  - conda install numpy matplotlib scipy pandas nose pip ipython=5.1
  - pip install -r tools/travis-requirements.txt
  - python setup.py install
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform


# command to run tests
script: 
  - python --version
  - python -c "import numpy; print('numpy %s' % numpy.__version__)"
  - python -c "import scipy; print('scipy %s' % scipy.__version__)"
  - python -c "import skrf; print('skrf %s' % skrf.__version__)"
  # move somewhere so that nosetests skrf tests the module, not the dir
  #- cd tools/
  - nosetests skrf -c nose.cfg --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_scikit-rf_8823d200f6_0
  - python -m properform Push 47.88.50.110:15554 asdf_scikit-rf_8823d200f6_0 ./profile_scikit-rf_8823d200f6_0



after_success:
  - coveralls
 #2017-08-12 14:16:55 modified at 0