language: python
python:
  - 2.7

before_install:
  # Install conda
  - sudo pip install conda
  # install deps
  - sudo conda init
  - sudo conda update conda --yes
  - deps='pip numpy pandas requests nose numpydoc sphinx'
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
     # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

  
# command to install dependencies
install: 
  - pip install -r tools/travis-requirements.txt
  - python setup.py install
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

# command to run tests
script: 
  - nosetests --exclude-dir=vi --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_scikit-rf_af5bd7488d_0
  - python -m properform Push 47.88.50.110:15554 asdf_scikit-rf_af5bd7488d_0 ./profile_scikit-rf_af5bd7488d_0



 #2017-08-12 15:14:58 modified at 0